In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [1]:
pip install apriori

Requirement already satisfied: apriori in c:\users\krujo\anaconda3\lib\site-packages (1.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_csv("TV Shows - Association Rule Learning.csv")

In [4]:
df

,Cobra Kai,Lupin,12 Monkeys,Sherlock,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,Lost,Jack Ryan,The Flash,Game of thrones,House of Cards,12 Monkeys,Vikings,Fringe,The Mentalist,The Alienist,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sex Education,Dr. House,Kingdom,The Walking Dead,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ozark,Sex Education,Constantine,Preacher,Vikings,The Tick,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Naruto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sex Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9684,One Piece,The Blacklist,Two and a half men,Lupin,Dark,How I met your mother,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9685,One Piece,Mr. Robot,Succession,Ozark,12 Monkeys,Vikings,The Vampire Diaries,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9686,Daredevil,Atypical,Heros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9687,Absentia,The Newsroom,The Alienist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9688,Atypical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.isnull().sum()

Cobra Kai         0
Lupin          2133
12 Monkeys     3743
Sherlock       5023
Unnamed: 4     6011
Unnamed: 5     6852
Unnamed: 6     7492
Unnamed: 7     8025
Unnamed: 8     8458
Unnamed: 9     8802
Unnamed: 10    9045
Unnamed: 11    9225
Unnamed: 12    9341
Unnamed: 13    9417
Unnamed: 14    9493
Unnamed: 15    9548
Unnamed: 16    9594
Unnamed: 17    9623
Unnamed: 18    9637
Unnamed: 19    9651
Unnamed: 20    9660
Unnamed: 21    9671
Unnamed: 22    9675
Unnamed: 23    9681
Unnamed: 24    9682
Unnamed: 25    9682
Unnamed: 26    9683
Unnamed: 27    9684
Unnamed: 28    9685
Unnamed: 29    9688
Unnamed: 30    9688
Unnamed: 31    9688
dtype: int64

In [6]:
df.shape

(9689, 32)

In [7]:
threshold = 9500
df = df.dropna(axis=1, thresh=len(df) - threshold + 1)

In [8]:
df = df.fillna("Unknown")

In [9]:
df

,Cobra Kai,Lupin,12 Monkeys,Sherlock,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Lost,Jack Ryan,The Flash,Game of thrones,House of Cards,12 Monkeys,Vikings,Fringe,The Mentalist,The Alienist,Big Little Lies,Chernobyl,Unknown,Unknown,Unknown
1,Sex Education,Dr. House,Kingdom,The Walking Dead,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,Ozark,Sex Education,Constantine,Preacher,Vikings,The Tick,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,Naruto,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,Sex Education,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9684,One Piece,The Blacklist,Two and a half men,Lupin,Dark,How I met your mother,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
9685,One Piece,Mr. Robot,Succession,Ozark,12 Monkeys,Vikings,The Vampire Diaries,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
9686,Daredevil,Atypical,Heros,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
9687,Absentia,The Newsroom,The Alienist,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
9688,Atypical,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [10]:
df.describe()

,Cobra Kai,Lupin,12 Monkeys,Sherlock,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
count,9689,9689,9689,9689,9689,9689,9689,9689,9689,9689,9689,9689,9689,9689,9689
unique,156,146,148,146,143,131,133,134,123,116,112,101,86,83,72
top,Daredevil,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
freq,811,2133,3743,5023,6011,6852,7492,8025,8458,8802,9045,9225,9341,9417,9493

In [11]:
df.shape

(9689, 15)

In [12]:
records = []
for i in range(0, 9689):
    records.append([str(df.values[i, j]) for j in range(0, 15)])

In [22]:
from apyori import apriori

association_rules = apriori(

    records, min_support=0.0045, min_confidence=0.6, min_lift=3, min_length=2)

association_results = list(association_rules)

In [23]:
association_results

[RelationRecord(items=frozenset({'Ozark', 'Demon Slayer', 'Family Guy'}), support=0.005573330581071318, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Demon Slayer', 'Family Guy'}), items_add=frozenset({'Ozark'}), confidence=0.6000000000000001, lift=3.0971763452317536)]),
 RelationRecord(items=frozenset({'Mr. Robot', 'Ozark', 'Succession'}), support=0.005779750232222107, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Mr. Robot', 'Succession'}), items_add=frozenset({'Ozark'}), confidence=0.6021505376344085, lift=3.108277335716454)]),
 RelationRecord(items=frozenset({'Mr. Robot', 'Ozark', 'The Blacklist', 'Atypical'}), support=0.005057281453194344, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Mr. Robot', 'The Blacklist', 'Atypical'}), items_add=frozenset({'Ozark'}), confidence=0.6125, lift=3.1617008524240813)]),
 RelationRecord(items=frozenset({'Mr. Robot', 'Ozark', 'Cobra Kai', 'Sex Education'}), support=0.005779750232222107, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Mr. Robot', 'Cobra Kai', 'Sex Education'}), items_add=frozenset({'Ozark'}), confidence=0.6292134831460674, lift=3.2479751935014636)]),
 RelationRecord(items=frozenset({'Mr. Robot', 'Ozark', 'The Blacklist', 'Cobra Kai'}), support=0.00454123232531737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Mr. Robot', 'The Blacklist', 'Cobra Kai'}), items_add=frozenset({'Ozark'}), confidence=0.7857142857142858, lift=4.055826166374915)]),
 RelationRecord(items=frozenset({'Mr. Robot', 'Ozark', 'Demon Slayer', 'Sex Education'}), support=0.005470120755495923, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Mr. Robot', 'Demon Slayer', 'Sex Education'}), items_add=frozenset({'Ozark'}), confidence=0.6162790697674418, lift=3.18120826157525)])]

In [24]:
print(len(association_results))

6

In [25]:
# print the rules, the support, the confidence, and lift for each rule
for item in association_results:

    # first index of the inner list
    # Contains base item and add item
    pair = item[0]
    items = [x for x in pair]
    print("Rule: " + items[0] + " -> " + items[1])

    # second index of the inner list
    print("Support: " + str(item[1]))

    # third index of the list located at 0th
    # of the third index of the inner list

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")

Rule: Ozark -> Demon Slayer
Support: 0.005573330581071318
Confidence: 0.6000000000000001
Lift: 3.0971763452317536
=====================================
Rule: Mr. Robot -> Ozark
Support: 0.005779750232222107
Confidence: 0.6021505376344085
Lift: 3.108277335716454
=====================================
Rule: Mr. Robot -> Ozark
Support: 0.005057281453194344
Confidence: 0.6125
Lift: 3.1617008524240813
=====================================
Rule: Mr. Robot -> Ozark
Support: 0.005779750232222107
Confidence: 0.6292134831460674
Lift: 3.2479751935014636
=====================================
Rule: Mr. Robot -> Ozark
Support: 0.00454123232531737
Confidence: 0.7857142857142858
Lift: 4.055826166374915
=====================================
Rule: Mr. Robot -> Ozark
Support: 0.005470120755495923
Confidence: 0.6162790697674418
Lift: 3.18120826157525
=====================================